export { default as Header } from "./Header.astro"
export { default as Badge } from "./Badge.astro"
export { default as BadgeRedes } from "./BadgeRedes.astro"
export { default as Home } from "./Home.astro"
export { default as About } from "./About.astro"
export { default as Card } from "./Card.astro"
export { default as BadgeNextJS } from "./BadgeNextJS.astro"
export { default as TechSkills } from "./TechSkills.astro"